# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  user: James
  password:
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: math_app_development

test:
  <<: *default
  database: math_app_test